namespace ProjectEnums
{
    public enum EAdvancedStat
    {
        INCREASED_STRENGTH,
        INCREASED_DEXTERITY,
        INCREASED_INTELLIGENCE,
        INCREASED_HEALTH,
        INCREASED_DAMAGE,
        INCREASED_ARMOUR,
        INCREASED_DODGE,
        INCREASED_MAGIC_RESISTANCE,
        DAMAGE_REDUCTION,
        BLOCK_CHANCE,
        BLOCK_DAMAGE_REDUCTION,
        HEALTH_REGEN,
        MANA_REGEN,
        INCREASED_PHYSICAL_DAMAGE,
        INCREASED_MAGIC_DAMAGE,
        INCREASED_SPELL_SKILL_DAMAGE,
        INCREASED_ATTACK_SKILL_DAMAGE,
        INCREASED_ATTACK_RANGE,
        INCREASED_ATTACK_SPEED,
        INCREASED_CAST_SPEED,
        ARMOUR_PENETRATION,
        MAGIC_DAMAGE_PENETRATION,
        ADDITIONAL_PROJECTILES, //TODO consider it
        LIFE_STEAL,
        BLEED_CHANCE,
        BURN_CHANCE,
        INCREASED_BLEED_CHANCE,
        INCREASED_BURN_CHANCE,
        INCREASED_SKILL_DURATION
    }
}